name: stasher_exam
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1

  # Network
  http: ^1.2.0
  json_serializable: ^6.8.0
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  dio: ^5.2.1+1

  # State Management
  provider: ^6.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  retrofit_generator: ^8.0.6
  flutter_gen_runner: ^5.3.0

flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

flutter:

  uses-material-design: true



  assets:
    - assets/images/
